/**
 * codeGenerator.ts
 *
 * Converts an array of ParsedStep objects into a complete, compilable
 * Java class with Cucumber step definition annotations.
 *
 * Responsibilities:
 *  - Emit the package declaration and all required imports
 *  - Generate each step's Javadoc, annotation, method signature, and body
 *  - Append shared helper methods used by most step implementations
 *  - Format the final source string so indentation is consistent
 *
 * This module contains no VS Code API calls; it is pure string
 * manipulation and can be unit-tested without a running extension host.
 */

import { ParsedStep, StepDefinitionConfig } from "../types/types";
import { parseStep } from "./step.parser";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Entry point for code generation.
 *
 * Takes raw step strings (already validated and deduplicated) and
 * emits a complete Java source file as a single string.
 *
 * @param steps  - Array of normalised Cucumber step strings.
 * @param config - User/workspace configuration controlling package name etc.
 * @returns Formatted Java source code ready to be written to disk or clipboard.
 */
export async function generateAdvancedStepDefinitions(
  steps: string[],
  config: StepDefinitionConfig,
): Promise<string> {
  const parsedSteps = steps.map((step) => parseStep(step));

  // Track used method names so duplicates receive a numeric suffix
  const methodNames = new Set<string>();

  const header = generateClassHeader(config);

  const body = parsedSteps
    .map((parsedStep) => {
      if (!parsedStep) {
        return "";
      }
      return generateAdvancedStepDefinition(parsedStep, methodNames, config);
    })
    .filter((def) => def !== "")
    .join("\n\n");

  const footer = generateClassFooter(config);

  return formatJavaCode(header + body + footer);
}

// ---------------------------------------------------------------------------
// Class-level emitters
// ---------------------------------------------------------------------------

/**
 * Generates the package declaration, import block, Javadoc comment,
 * class declaration, and field/constructor boilerplate.
 *
 * @param config - Extension configuration.
 * @returns Partial Java source string covering everything before the first method.
 */
function generateClassHeader(config: StepDefinitionConfig): string {
  let header = "";

  // Package declaration
  if (config.packageName) {
    header += `package ${config.packageName};\n\n`;
  }

  // Merge default imports with any user-supplied extras,
  // deduplicating so the same import is never emitted twice.
  const defaultImports = [
    "io.cucumber.java.en.Given",
    "io.cucumber.java.en.When",
    "io.cucumber.java.en.Then",
    "org.openqa.selenium.WebDriver",
    "org.openqa.selenium.WebElement",
    "org.openqa.selenium.By",
    "org.openqa.selenium.support.ui.Select",
    "org.openqa.selenium.support.ui.WebDriverWait",
    "org.testng.Assert",
    "java.time.Duration",
  ];

  const allImports = [...new Set([...defaultImports, ...config.imports])];
  allImports.forEach((imp) => {
    header += `import ${imp};\n`;
  });

  header += "\n";

  // Class-level Javadoc
  header += `/**\n`;
  header += ` * Cucumber Step Definitions\n`;
  header += ` * Generated by Selenium-Cucumber Extension\n`;
  header += ` *\n`;
  header += ` * Each method maps to one or more Gherkin steps.\n`;
  header += ` * Replace the TODO comments with your actual Selenium logic.\n`;
  header += ` */\n`;

  // Class declaration — optionally extends a base test class
  if (config.baseTestClass) {
    header += `public class ${config.className} extends ${config.baseTestClass} {\n\n`;
  } else {
    header += `public class ${config.className} {\n\n`;
  }

  // Common fields every step class will need
  header += `    /** Shared WebDriver instance — inject or initialise in the constructor. */\n`;
  header += `    private WebDriver driver;\n`;
  header += `\n`;
  header += `    /** Fluent wait wrapper for synchronisation helpers. */\n`;
  header += `    private WebDriverWait wait;\n\n`;

  // Default constructor with setup guidance
  header += `    /**\n`;
  header += `     * Default constructor.\n`;
  header += `     * Uncomment the lines below once a DriverManager is in place.\n`;
  header += `     */\n`;
  header += `    public ${config.className}() {\n`;
  header += `        // this.driver = DriverManager.getDriver();\n`;
  header += `        // this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));\n`;
  header += `    }\n\n`;

  return header;
}

/**
 * Generates the closing brace and shared helper methods that most
 * step implementations will delegate to.
 *
 * @param config - Extension configuration (reserved for future use).
 * @returns Partial Java source string covering everything after the last step method.
 */
function generateClassFooter(config: StepDefinitionConfig): string {
  let footer = "\n";

  // Helper: wait for an element before returning it
  footer += `    /**\n`;
  footer += `     * Waits for the element identified by {@code locator} to be present\n`;
  footer += `     * and returns it. Uses the shared {@link #wait} instance.\n`;
  footer += `     *\n`;
  footer += `     * @param locator - Selenium By locator.\n`;
  footer += `     * @returns The located WebElement.\n`;
  footer += `     */\n`;
  footer += `    private WebElement findElementWithWait(By locator) {\n`;
  footer += `        return wait.until(driver -> driver.findElement(locator));\n`;
  footer += `    }\n\n`;

  // Helper: safe visibility check that swallows NoSuchElementException
  footer += `    /**\n`;
  footer += `     * Returns true if the element exists in the DOM and is visible;\n`;
  footer += `     * returns false instead of throwing when the element is absent.\n`;
  footer += `     *\n`;
  footer += `     * @param locator - Selenium By locator.\n`;
  footer += `     * @returns true if the element is displayed, false otherwise.\n`;
  footer += `     */\n`;
  footer += `    private boolean isElementDisplayed(By locator) {\n`;
  footer += `        try {\n`;
  footer += `            return driver.findElement(locator).isDisplayed();\n`;
  footer += `        } catch (Exception e) {\n`;
  footer += `            return false;\n`;
  footer += `        }\n`;
  footer += `    }\n`;

  footer += "}\n";

  return footer;
}

// ---------------------------------------------------------------------------
// Method-level emitters
// ---------------------------------------------------------------------------

/**
 * Generates the complete Javadoc + annotation + method body for a single step.
 *
 * If an identical camelCase name has already been used, a numeric suffix
 * (1, 2, 3 …) is appended to keep all method names unique within the class.
 *
 * @param parsedStep  - Structured step data produced by stepParser.
 * @param methodNames - Mutable set of already-claimed method names.
 * @param config      - Extension configuration.
 * @returns A string containing the full Java method source, indented at 4 spaces.
 */
function generateAdvancedStepDefinition(
  parsedStep: ParsedStep,
  methodNames: Set<string>,
  config: StepDefinitionConfig,
): string {
  // Resolve a unique method name by appending a counter when needed
  let uniqueMethodName = parsedStep.methodName;
  let counter = 1;
  while (methodNames.has(uniqueMethodName)) {
    uniqueMethodName = `${parsedStep.methodName}${counter}`;
    counter++;
  }
  methodNames.add(uniqueMethodName);

  const parametersList = parsedStep.parameters.join(", ");

  let method = "";

  // Javadoc block
  method += `    /**\n`;
  method += `     * Step: ${parsedStep.originalStep}\n`;
  if (parsedStep.parameters.length > 0) {
    method += `     * Parameters: ${parsedStep.parameters.length}\n`;
  }
  method += `     */\n`;

  // Cucumber annotation with regex pattern
  method += `    @${parsedStep.annotation}("^${parsedStep.parameterizedRegex}$")\n`;

  // Method signature
  method += `    public void ${uniqueMethodName}(${parametersList}) {\n`;

  // Try-catch wrapper with TODO comment and template body
  method += `        try {\n`;
  method += `            // TODO: Implement step logic for: ${parsedStep.stepText}\n`;

  // List extracted parameters as inline documentation
  if (parsedStep.parameters.length > 0) {
    method += `            // Available parameters:\n`;
    parsedStep.parameters.forEach((param) => {
      method += `            //   ${param}\n`;
    });
  }

  // Emit a contextual code scaffold based on annotation type and step text
  method += generateStepTemplate(parsedStep.annotation, parsedStep.stepText);

  method += `\n`;
  method += `            // Add assertions for verification\n`;
  method += `            // Assert.assertTrue("Step verification failed", condition);\n`;
  method += `\n`;
  method += `        } catch (Exception e) {\n`;
  method += `            throw new RuntimeException("Failed to execute step: ${parsedStep.stepText}", e);\n`;
  method += `        }\n`;
  method += `    }`;

  return method;
}

/**
 * Returns a short comment scaffold tailored to the step's annotation type
 * and common keywords found in the step text.
 *
 * The scaffold is intentionally left as comments so the developer can
 * uncomment and adapt rather than overwriting working code.
 *
 * @param annotation - "Given", "When", or "Then".
 * @param stepText   - The human-readable step text without the keyword.
 * @returns Indented comment lines ending with a newline.
 */
function generateStepTemplate(annotation: string, stepText: string): string {
  let template = "";
  const lower = stepText.toLowerCase();

  switch (annotation.toLowerCase()) {
    case "given":
      template += `            // Setup / precondition logic\n`;
      if (lower.includes("navigate") || lower.includes("open")) {
        template += `            // driver.get("URL");\n`;
      } else if (lower.includes("login") || lower.includes("user")) {
        template += `            // Perform login or user setup\n`;
      } else {
        template += `            // Initialise test data or application state\n`;
      }
      break;

    case "when":
      template += `            // Action / interaction logic\n`;
      if (lower.includes("click")) {
        template += `            // WebElement element = driver.findElement(By.id("elementId"));\n`;
        template += `            // element.click();\n`;
      } else if (lower.includes("enter") || lower.includes("input")) {
        template += `            // WebElement inputField = driver.findElement(By.id("inputId"));\n`;
        template += `            // inputField.sendKeys("value");\n`;
      } else if (lower.includes("select")) {
        template += `            // Select dropdown = new Select(driver.findElement(By.id("selectId")));\n`;
        template += `            // dropdown.selectByVisibleText("optionText");\n`;
      } else {
        template += `            // Perform the main action\n`;
      }
      break;

    case "then":
      template += `            // Verification / assertion logic\n`;
      if (lower.includes("should see") || lower.includes("displayed")) {
        template += `            // WebElement element = driver.findElement(By.id("elementId"));\n`;
        template += `            // Assert.assertTrue("Element should be displayed", element.isDisplayed());\n`;
      } else if (lower.includes("text") || lower.includes("contains")) {
        template += `            // String actualText = driver.findElement(By.id("elementId")).getText();\n`;
        template += `            // Assert.assertTrue("Text mismatch", actualText.contains("expectedText"));\n`;
      } else {
        template += `            // Verify the expected outcome\n`;
      }
      break;

    default:
      template += `            // Implement step logic\n`;
  }

  return template;
}

// ---------------------------------------------------------------------------
// Formatter
// ---------------------------------------------------------------------------

/**
 * Applies simple indentation normalisation to the generated Java source.
 *
 * The generator emits lines with hardcoded leading spaces which can fall
 * out of sync if nested blocks shift the expected indent level. This pass
 * re-calculates indentation from scratch by counting opening and closing
 * braces.
 *
 * @param code - Raw Java source string.
 * @returns Reformatted Java source string with consistent 4-space indentation.
 */
export function formatJavaCode(code: string): string {
  const INDENT_SIZE = 4;
  let indentLevel = 0;

  const formattedLines = code.split("\n").map((line) => {
    const trimmed = line.trim();

    if (!trimmed) {
      return "";
    }

    // Decrease indent before rendering closing braces
    if (trimmed === "}" || trimmed.startsWith("} ")) {
      indentLevel = Math.max(0, indentLevel - 1);
    }

    const indentedLine = " ".repeat(indentLevel * INDENT_SIZE) + trimmed;

    // Increase indent after lines that open a new block
    if (trimmed.endsWith("{")) {
      indentLevel++;
    }

    return indentedLine;
  });

  return formattedLines.join("\n");
}
